" KISS me
set autoindent
set expandtab
set number
set numberwidth=4
set shiftwidth=4
set smartindent
set softtabstop=4
set tabstop=4
set backspace=indent,eol,start
set hlsearch
set incsearch
set ignorecase
set smartcase
set history=700
set whichwrap=<,>,[,]
set scrolloff=999
set sidescroll=999
set cursorline
set novisualbell
colorscheme murphy
syntax on